### ISSUE TITLE
dash - governance

### ISSUE THREAD

**Issue by carchrae** [Finhaven/whitepaper-club#25]
# Why This is Interesting
Dash has an interesting governance system that funds development.

# Link to Paper(s)
* https://github.com/dashpay/dash/wiki/Whitepaper
* https://dashpay.atlassian.net/wiki/spaces/DOC/pages/8585240/Understanding+the+Governance+and+Budget+System

# Additional Resources
* https://www.dash.org/governance/
* https://dashpay.atlassian.net/wiki/spaces/DOC/pages/1146914/What+is+Dash

**Comment by expede** [comment]
Closed by https://github.com/Finhaven/whitepaper-club/pull/34
