### ISSUE TITLE
decred - atomic swap (repo)

### ISSUE THREAD

**Issue by carchrae** [Finhaven/whitepaper-club#28]
# Why This is Interesting
Decred have some code that shows how to trade across chains (the atomic swap), eg, trade some Decred for LTC,  or BTC for Decred.

# Link to Paper(s)
* don't know of any papers - anyone?  just https://github.com/decred/atomicswap/blob/master/README.md

# Additional Resources (optional)
* [Github](https://github.com/decred/atomicswap)

**Comment by BenMorganIO** [comment]
That's really cool of decred. What's also nice is it's dual mining features as well with coins such as ethereum.

Decreds ability to basically "exchange" a currency would make it quite suitable for miners when coins such as MusicCoin or Zcash appear as great to mine. This makes it a great option when trying to opt-out odd services such as Changelly or ShapeShift.

Just my $0.02.

**Comment by expede** [comment]
Presented March 8, 2018
